config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events do
    resources :attendees_events, only: [:new, :create, :destroy]
    member do
      get 'attend'
      get 'unattend'
    end
  end

  get '/users/:id/' => 'users#show', :as => :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendees_event.rb
class AttendeesEvent < ApplicationRecord
  validates_uniqueness_of :attendee_id, scope: :event_id
  belongs_to :attendee, class_name: 'User'
  belongs_to :event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { where("date < ?", Date.today) } 
  scope :upcoming, -> { where("date >= ?", Date.today) }

  validates :date, :theme, presence: true

  belongs_to :creator, class_name: "User"
  has_many :attendees_events, dependent: :destroy
  has_many :attendees, through: :attendees_events, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true

  has_many :created_events, foreign_key: :creator_id, class_name: "Event", dependent: :destroy
  has_many :attendees_events, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendees_events, source: :event, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendees_events_controller.rb
class AttendeesEventsController < ApplicationController
  private

  def attendees_event_params
    params.require(:attendees_event).permit(:event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :past]

  # GET /events or /events.json
  def index
    @events = Event.all.order('created_at DESC')
    @event = Event.new
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.created_events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def attend
    @event = Event.find(params[:id])

    attendees_events = AttendeesEvent.new(attendee_id: current_user.id, event_id: @event.id)
    if attendees_events.save
      redirect_to @event, notice: "You are now attending this event!"
    else
      redirect_to @event, alert: "You are already attending this event!"
    end
  end
  
  def unattend
    @event = Event.find(params[:id])

    attendees_events = AttendeesEvent.find_by(attendee_id: current_user.id, event_id: @event.id)
    attendees_events.destroy
    
    redirect_to @event, notice: "You are no longer attending this event!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:date, :theme, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_User, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /Users or /Users.json
  def index
    @users = User.all.order('created_at DESC')
    @user = User.new
  end

  # GET /Users/1 or /Users/1.jsons
  def show
  end

  # GET /Users/new
  def new
    @user = current_user.Users.build
  end

  # GET /Users/1/edit
  def edit
  end

  # POST /Users or /Users.json
  def create
    @user = current_user.Users.build(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Users/1 or /Users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Users/1 or /Users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_User
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def User_params
      params.require(:user).permit(:date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="card">
  <header class="card-header">
    <p class="card-header-title"> 
      <%= event.theme %>
    </p>
  </header>

  <div class="card-content">
    <div class="content">
      <p><%= event.description %></p>
      <time datetime="">Event date: <%= event.date %></time>
    </div>  
  </div>

  <footer class="card-footer">
    <%= link_to "Show this event", event, class: "card-footer-item" %>
    <%= link_to event.creator.username, event.creator, class: "card-footer-item" %>
  </footer>
</div>

app/views/events/_form.html.erb
<div class="section">
  <div class="container">
  <div class="columns is-centered">

      <div class="column is-4">

      <%= simple_form_for @event do |form| %>
        <% if @event.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
              <% event.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <div class="control">
            <%= form.input :theme, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

         <div class="field">
          <div class="control">
            <%= form.input :description, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

         <div class="field">
          <div class="control">
            <%= form.input :date, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= form.button :submit, "Create Event", class:"button is-info is-medium" %>
          </div>
        </div>

      <% end %>
      	</div>
		</div>
	</div>
</div> 

app/views/events/edit.html.erb
<h2 class="title is-2">Edit Event</h2>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <div id="events">
      <div class="columns">
        <div class="column">
          <h2 class="title is-4">Upcoming Events</h2>
          <% @events.upcoming.each do |event| %>
            <%= render event %>
          <% end %>
        </div>
        <div class="column">
          <h2 class="title is-4">Passed Events</h2>
          <% @events.past.each do |event| %>
            <%= render event %>
          <% end %>
        </div>
      </div>  
    </div> 
  </div>
</section>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
      <h2 class="title is-2">New Event</h2>
      <%= render "form", event: @event %>
      <%= link_to "Back to events", events_path %>  
  </div>
</section>

app/views/events/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <%= render @event %>
      
        <div class="block" id="controller">
          
          <% if user_signed_in? && current_user.id == @event.creator_id %>
            <%= link_to "Edit this event", edit_event_path(@event) %>
            <%= button_to "Destroy this event", @event, method: :delete, class:"button is-info" %>
          <% end %>
        </div>
      </div>
      <div class="column">
        <% if @event.date.past? %>
            <button class="button is-danger is-medium mb-4 attend-btn" disabled>
                Event Has Passed!
            </button>
        <% else %>
            <% if  user_signed_in? && AttendeesEvent.exists?(attendee_id: current_user.id, event_id: @event.id) %>
                <%= link_to 'Unattend', unattend_event_path(@event.id), 
                                        class: "attend-btn button is-danger is-light mb-4 is-medium" %>
            <% else %>
                <%= link_to 'Attend', attend_event_path(@event.id), 
                                    class: "attend-btn button is-danger mb-4 is-medium" %>
            <% end %>
        <% end %>
        <div class="box">
          <div class="media">
            <div class="media-left">
              <img src="https://img.icons8.com/material-outlined/50/000000/clock--v1.png"/>
            </div>
            <div class="media-content">
              <p> <%=@event.date.strftime("%A, %B %d, %Y ")%> </p>
            </div>
          </div>
        </div>
      </div>
      <div class="column" id="attendees">
        <div class="block attendees">
          <h3 class="title"> Attendees (<%= @event.attendees.count %>) </h3>
          <div class="columns is-multiline is-variable is-mobile">
            <% @event.attendees.each do |attendee| %>
              <div id="attendee-card" class="column is-one-quarter-fullhd is-one-quarter-widescreen is-one-third-desktop is-two-fifths-tablet is-half-mobile ">
                <%= link_to user_path(attendee.id) do %>
                  <div class="card ">
                    <div class="card-content">
                      <p class="has-text-weight-semibold has-text-centered"> <%= attendee.username %> </p>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %> 
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

     <nav class="navbar is-info">
      <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-5">Private Events</h1>
          <% end %> 
          <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
          </div> 
        </div>

        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to 'New event', new_event_path, class: "button is-info is-inverted" %>
                </p>
                <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.username, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= button_to("Logout", destroy_user_session_path, method: :delete, class:"button is-info") %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <h2 class="title is-4">Users Events</h2>
        <div id="events">
          <% @user.created_events.each do |event| %>
            <%= render event %>
          <% end %>
        </div>
      </div>
      <div class="column">
        <h2 class="title is-4">Attended Events (<%= @user.attended_events.count %>) </h2>
        <div id="events">
          <% @user.attended_events.each do |event| %>
            <%= render event %>
          <% end %>
        </div> 
      </div>
    </div>
  </div>
</section>  